In [1]:
import numpy as np

In [2]:
##Zero

zeroc = np.zeros(10)
display(zeroc)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
##diagonal

Dia = np.eye(3,5)
display(Dia)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [5]:
#line space
li = np.linspace(0,20,5)
display(li)

array([ 0.,  5., 10., 15., 20.])

In [7]:
# rand generte betwwen 0,1
var = np.random.rand(4)
var1 = np.random.rand(2,5)
display(var)
display(var1)

array([0.39750708, 0.87105284, 0.34920361, 0.96139807])

array([[0.89718421, 0.68854101, 0.8981213 , 0.24083078, 0.05722975],
       [0.20623663, 0.67433122, 0.65486905, 0.22474058, 0.77812533]])

In [8]:
# randn generte between negitive and poistion but close to zero and
r = np.random.randn(10)
display(r)

array([-0.7624346 , -0.71798614,  0.00567886,  1.33701022,  1.5963516 ,
       -1.060636  ,  0.3937502 , -1.93885869, -0.93433274, -2.14416586])

In [9]:
# ranf generte between interval [0.0, 1.0)
r1 = np.random.ranf(10)
display(r1)

array([0.64003752, 0.82992472, 0.12950625, 0.1184315 , 0.540796  ,
       0.42460942, 0.09666602, 0.95642678, 0.81089583, 0.38550118])

In [11]:
#randint generate between interval give min and max values from
r2 = np.random.randint(1,250,10)
display(r2)

array([233, 139, 108, 189, 244, 140, 177, 113, 214, 115])

In [12]:
#Arithmetic Operation

var = np.array([1,2,3,4,5])

varadd = var + 3
display(varadd)

array([4, 5, 6, 7, 8])

In [18]:
var = np.array([1,2,3,4,5])
var2 = np.ones_like(var)
varadd = np.add(var,var2)
display(varadd)

array([2, 3, 4, 5, 6])

In [13]:
var = np.array([1,2,3,4,5])
var2 = np.ones_like(var)
varadd = var + var2
display(varadd)

array([2, 3, 4, 5, 6])

In [14]:
var = np.array([1,2,3,4,5])

varadd = var - 3
display(varadd)

array([-2, -1,  0,  1,  2])

In [15]:
var = np.array([1,2,3,4,5])
var2 = np.ones_like(var)
varadd = var - var2
display(varadd)

array([0, 1, 2, 3, 4])

In [16]:
var = np.array([1,2,3,4,5])

varadd = var / 3
display(varadd)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [17]:
var = np.array([1,2,3,4,5])

varadd = var % 3
display(varadd)

array([1, 2, 0, 1, 2], dtype=int32)

In [25]:
#2D Array

var = np.arange(2*5).reshape(2,5)
var1 = np.arange(2*5).reshape(2,5)
varadd = np.multiply(var,var1) 
display(varadd)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [26]:
var = np.arange(2*5).reshape(2,5)
varadd = np.reciprocal(var) 
display(varadd)

D:\temp\ipykernel_4056\200310899.py:3: RuntimeWarning: divide by zero encountered in reciprocal
  varadd = np.reciprocal(var)
D:\temp\ipykernel_4056\200310899.py:3: RuntimeWarning: invalid value encountered in reciprocal
  varadd = np.reciprocal(var)


array([[-2147483648,           1,           0,           0,           0],
       [          0,           0,           0,           0,           0]])

In [30]:
# Arithmetic function
var = np.array([1,2,3,4,5,45,23,2,1])
display("Min",np.min(var),np.argmin(var))
display("Max",np.max(var),np.argmax(var))
display("SQR",np.sqrt(var))

'Min'

1

0

'Max'

45

5

'SQR'

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       6.70820393, 4.79583152, 1.41421356, 1.        ])

In [29]:
#min axis 

var = np.array([[1,2,3],[4,5,6]])
display(np.min(var,axis=1))
display(np.max(var,axis=1))

array([1, 4])

array([3, 6])

In [34]:
#sin cos consum

var2 = np.array([1,2,3])
display(np.sin(var2))
display(np.cos(var2))
display(np.cumsum(var2))

array([0.84147098, 0.90929743, 0.14112001])

array([ 0.54030231, -0.41614684, -0.9899925 ])

array([1, 3, 6])

In [35]:
#nditer
var = np.array([[1,2,3],[4,5,6]])

for i in np.nditer(var):
    display(i)


array(1)

array(2)

array(3)

array(4)

array(5)

array(6)

In [36]:
#ndenumator
var = np.array([[1,2,3],[4,5,6]])

for i,v in np.ndenumerate(var):
    display(i,v)

(0, 0)

1

(0, 1)

2

(0, 2)

3

(1, 0)

4

(1, 1)

5

(1, 2)

6

In [39]:
# Search Where
var = np.array([1,2,3,4,5,2,7,865,5,43,3,2])
x = np.where(var == 2)
print(x)

(array([ 1,  5, 11], dtype=int64),)


In [43]:
varw = np.array([4,2,3,4,5,2,7,865,5,43,3,2])
x = np.where((varw%2) == 0)
print(x)

(array([ 0,  1,  3,  5, 11], dtype=int64),)


In [44]:
#search Sort array contain Binary array
vars = np.array([1,2,3,4,7,8,9])
x = np.searchsorted(vars,5)
print(x)

4
